[build]
  command = "npm run build"
  publish = "dist"

[context.production.environment]
  ELEVENTY_ENV = "production"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer-when-downgrade"
    Strict-Transport-Security= "max-age=63072000; includeSubDomains; preload"

[[headers]]
  for = "/assets/*"
  [headers.values]
    cache-control = '''
      public,
      max-age=31536000,
      immutable'''

# For when we do English language too
# [[redirects]]
#   from = "/"
#   to = "/en/"
#   condition = {Language = ["en"]}

[[redirects]]
  from = "/"
  to = "/nl/"

# For when we do English language too
# [[redirects]]
#   from = "/nl/*"
#   to = "/nl/404"
#   status = 404

# [[redirects]]
#   from = "/en/*"
#   to = "/en/404"
#   status = 404

[[redirects]]
  from = "/*"
  to = "/404/"
  status = 404
